### ISSUE TITLE
Support of current lang

### ISSUE THREAD

**Issue by dragomano** [T-miracle/vitepress-plugin-comment-with-giscus#12]
Add support of current lang for `lang` option in `giscusTalk` for docs with language switcher

**Comment by T-miracle** [comment]
thx feedback, README has been updated.
You can now check available language options through the official link.

**Comment by dragomano** [comment]
I think I expressed my point incorrectly. I have 4 languages on my site. How do I automatically switch the language of the comments widget when I switch the site language?

**Comment by T-miracle** [comment]
> I think I expressed my point incorrectly. I have 4 languages on my site. How do I automatically switch the language of the comments widget when I switch the site language?

Which way do you use to switch languages? This may require additional implementations

**Comment by dragomano** [comment]
Standard language switcher from Vitepress

**Comment by T-miracle** [comment]
> Standard language switcher from Vitepress

OK, It might take a little while to try and implement that feature, I'll keep this issue open and get back to you when it's done.

**Comment by T-miracle** [comment]
> Standard language switcher from Vitepress

Updated, please upgrade to the latest version. Refer to the documentation for usage instructions.
