### ISSUE TITLE
categoryId - Property in Readme

### ISSUE THREAD

**Issue by Stuyk** [T-miracle/vitepress-plugin-comment-with-giscus#2]
I missed this one, but the `categoryId` in the configuration is incorrect.

You have it specified as just `category` in the props.

Just needs to be clarified.

![](https://i.imgur.com/1GMY8t4.png)

![](https://i.imgur.com/gMLkSyI.png)

**Comment by T-miracle** [comment]
@Stuyk ok，I'll add `category` props description  to the document later
