### ISSUE TITLE
你好，大佬，能否给这个功能增加一个开关

### ISSUE THREAD

**Issue by jackloves111** [T-miracle/vitepress-plugin-comment-with-giscus#3]
在vitepress文档内评论之后，会将vuepress的文档访问地址自动回复Discussion 内，当然这个功能非常便捷。但是我不想这么做，请问有什么办法关闭这个功能吗？

**Comment by T-miracle** [comment]
@jackloves111 抱歉，我没有在Giscus官方配置中找到有关 **关闭地址显示** 功能的配置选项，你可以在[Giscus官方提问社区](https://github.com/giscus/giscus/issues)询问一下
