### ISSUE TITLE
能否加个属性默认全部关闭评论

### ISSUE THREAD

**Issue by anghunk** [T-miracle/vitepress-plugin-comment-with-giscus#4]
目前是默认全部开启评论，使用 `comment: false` 关闭当前页面评论。

能否加个属性，设置为全部页面关闭评论，单页面如果有 `comment: true` 则开启， `comment: false` 或者不写 则为关闭

**Comment by T-miracle** [comment]
@98zi 可以，有空余时间我修改一下，到时候通知你

**Comment by T-miracle** [comment]
@98zi 版本1.1.8已更新，是否全局启用配置已添加，详细查看[配置文档](https://github.com/T-miracle/vitepress-plugin-comment-with-giscus/blob/main/README_zh.md)

**Comment by anghunk** [comment]
> @98zi 版本1.1.8已更新，是否全局启用配置已添加，详细查看[配置文档](https://github.com/T-miracle/vitepress-plugin-comment-with-giscus/blob/main/README_zh.md)

感谢升级。
