### ISSUE TITLE
Discussion not found

### ISSUE THREAD

**Issue by chunge16** [T-miracle/vitepress-plugin-comment-with-giscus#5]
<img width="1303" alt="image" src="https://github.com/T-miracle/vitepress-plugin-comment-with-giscus/assets/16758420/bfe54256-04ef-49dd-8012-b6c9b386b541">

why Discussion not found ?

**Comment by T-miracle** [comment]
已经好了，今天Giscus官方有点抽风，没法用，也有可能Github对评论社区更新了点啥，但是现在已经正常了

**Comment by T-miracle** [comment]
> 已经好了，今天Giscus官方有点抽风，没法用，也有可能Github对评论社区更新了点啥，但是现在已经正常了

@chunge16 你现在试试看正不正常

**Comment by chunge16** [comment]
mapping: 'specific', // 默认: `pathname`

**Comment by chunge16** [comment]
我查看 官方

**Comment by chunge16** [comment]
我看了 [giscus-component](https://github.com/giscus/giscus-component#giscus-component) 的例子，

`
 mapping: 'specific', // 默认: `pathname`

`
giscus 才可以请求成功

**Comment by chunge16** [comment]
mapping: 'pathname', // 默认:pathname` ，mapping为  pathname，新增评论接口会报错

<img width="1633" alt="image" src="https://github.com/T-miracle/vitepress-plugin-comment-with-giscus/assets/16758420/5c1cc46b-16a4-4ab6-a2b8-18186431f4dd">

**Comment by T-miracle** [comment]
> mapping: 'pathname', // 默认:pathname` ，mapping为 pathname，新增评论接口会报错
> 
> <img alt="image" width="1633" src="https://user-images.githubusercontent.com/16758420/281112141-5c1cc46b-16a4-4ab6-a2b8-18186431f4dd.png">

你发送配置我看一下

**Comment by chunge16** [comment]
```
                repo: 'chunge16/vitepress-blogs',
                repoId: 'R_kgDOKFcWWg',
                category: 'Announcements',
                categoryId: 'IC_kwDOKFcWWs4Cav-V',
                mapping: 'pathname', // 默认: `pathname`
                inputPosition: 'top', // 默认: `top`
                lang: 'zh-CN', // 默认: `zh-CN`
                strict: '0',
                reactionsEnabled: "1",
                emitMetadata: "0",
                loading: "lazy",
                crossorigin: "anonymous",
```

**Comment by chunge16** [comment]
```html
<script src="https://giscus.app/client.js"
        data-repo="chunge16/vitepress-blogs"
        data-repo-id="R_kgDOKFcWWg"
        data-category="Announcements"
        data-category-id="DIC_kwDOKFcWWs4Cav-V"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
```

**Comment by chunge16** [comment]
不好意思，categoryId字段我弄错了，已经OK了，感谢你的回复

**Comment by T-miracle** [comment]
> 不好意思，categoryId字段我弄错了，已经OK了，感谢你的回复

我刚想说，尽量不要用Announcements，这是用于公告的，平常都是用General，当然可以重新建一个，我刚本地测试Announcements也是会出问题的

当然，如果你已经解决了可以忽略我说的
